### ISSUE TITLE
Feature: Import csv Files

### ISSUE THREAD

**Issue by madaxel** [rrrapha/translate_locallang#14]
Hi @rrrapha,
I think it would be great to import the previously exported CSV Files.

**Comment by rrrapha** [comment]
Hi @madaxel, thanks for your pull request!
I've pushed a branch 'importCVS' with a different implementation.
The main difference is that the labels are loaded to the UI, and not saved automatically on import.

Would this work for you?

**Comment by madaxel** [comment]
Hi @rrrapha ,
works for me, just uploaded and saved ;-) 
Thx
