### ISSUE TITLE
Extension list is empty

### ISSUE THREAD

**Issue by brotkrueml** [rrrapha/translate_locallang#18]
I installed the extension via composer on TYPO3 9.5.4 as a development requirement. When I navigate to the module, the "Select extension" dropdown is empty. Of course I have multiple extensions installed (local extensions via symlink in typo3conf/ext/).

**Comment by rrrapha** [comment]
Hi, I am unable to reproduce this issue.
I guess it has something to do with this function:
https://github.com/rrrapha/translate_locallang/blob/57dfda6bfbd9471e46ac1a4231d08569ab96f539/Classes/Utility/TranslateUtility.php#L168
Could you check if the return value of `getConfigPath()` is correct on your system?

**Comment by rrrapha** [comment]
The issue should be fixed in the latest version.
@brotkrueml Thanks for reporting!
