### ISSUE TITLE
Feature: New XLF files from the BE module

### ISSUE THREAD

**Issue by nostadt** [rrrapha/translate_locallang#20]
I think it would be handy if XLF files could be created right from the BE module. What do you think about it?

**Comment by rrrapha** [comment]
I've added this feature in the develop branch. Can you please test it?

**Comment by nostadt** [comment]
Nice. It works. Tested it with `.ddev`, `ngnx/1.14.2`, `php 7.2.16` and a kinda plain `t3 env`. 👍  Are there other types than `xlf` to expect? If not I suggest to make the file ending optional.

**Comment by rrrapha** [comment]
Thanks for testing.
No, there are no other types than xlf expected, but I'm not a big fan of the windows-style hiding of file extensions, so I'll keep it as is.
