### ISSUE TITLE
RFC: Feature: Add regex for ext-filter

### ISSUE THREAD

**Issue by nostadt** [rrrapha/translate_locallang#21]
What do you think of a regex for the ext-filter?

Assuming I have a bunch of third party ext. installed and don't want to edit these in the future by overriding them to use my own. As of the moment every ext. have to be added to a whitelist which can be quite bothersome. Each time you add a new custom ext. this list has to be updated. On top this effects non admins only.

If you're an admin and want to maintain translations of your own ext. solely it can become bothersome to seek for the extension in the possible long dropdown.

Now, a regex could come in handy. Sth. like: editPreFilter: `acme_*`
This filter would apply for everyone e.g. In the dropdown solely ext. starting with `acme_` are listed.

Of course the current access management have to be kept in mind and overall it should not get too complex for a simple translation tool. An other idea is to add such a filter to the view and the filter is saved for current session.

**Comment by rrrapha** [comment]
Hi @AMartinNo1 
Thanks, this is good idea, I'll look into this soon.

**Comment by rrrapha** [comment]
I have added such a feature to the develop branch, .. I wonder if it works for you ;)

**Comment by nostadt** [comment]
Cool, will check it out next week as I have time :)

**Comment by nostadt** [comment]
Nice :)

**Comment by nostadt** [comment]
@rrrapha I just had following idea: As an admin a short note within the translation view and nearby the dropdown could be helpful: 'Ext filter with regex "acme_*" is active'. Especially for new admins who join a project may not be aware of that and wonder why not every ext. is listed. I would not display it for non-admins though as they should not know the other available ext. However, admins should be aware I believe.

**Comment by rrrapha** [comment]
@AMartinNo1 Thanks, I committed something like this..
The filter pattern is now displayed inside the dropdown (after 'Select extension'). 
(Note that it is not a 'regex' expression, it uses fnmatch)

**Comment by nostadt** [comment]
@rrrapha "fnmatch": I see

Will approx check it out on Sunday :)

**Comment by nostadt** [comment]
Got a free minute to test @rrrapha :)
I tested it with `extFilter=acme_*` and `allowedExts=acme_demo`. As non-admin user I see the active filter and `acme_demo` active only.

I would not show `extFilter` for non-admin users or at least hide it if a non-admin filter `allowedExts` applies.

**Comment by rrrapha** [comment]
> I would not show `extFilter` for non-admin users or at least hide it if a non-admin filter `allowedExts` applies.

Right, I missed this bit.. should be fixed now, thanks!

**Comment by nostadt** [comment]
@rrrapha Looks good :)
