### ISSUE TITLE
CDATA support

### ISSUE THREAD

**Issue by dogawaf** [rrrapha/translate_locallang#23]
Hello

When a XLIFF file contains xml entities, the node value must be enclosed in CDATA.

Translate module should interpret CDATA properly when loading and saving the files

**Comment by rrrapha** [comment]
Hi @dogawaf
Can you explain what you think is wrong with the CDATA handling?
I just tested the following and I believe the resulting xml is correct.

![cdata](https://user-images.githubusercontent.com/20947558/57308270-57d6e180-70e6-11e9-870f-f8591da6d27d.png)

The xml looks like this:
```
<trans-unit id="label0">
	<source>&amp;</source>
</trans-unit>
<trans-unit id="label1">
	<source>&lt;</source>
</trans-unit>
<trans-unit id="label2">
	<source><![CDATA[ & ]]></source>
</trans-unit>
```

**Comment by dogawaf** [comment]
CDATA should not be presented to the user. It must be used in the XML reading/writing in order to allow html/XML entities to be stored in a valid way.

**Comment by rrrapha** [comment]
I don't think this is possible at all. The tool cannot know if you want to use CDATA or not. 
I was thinking about adding a CDATA-checkbox next to the textareas, but I don't think it is worth doing. 
(Most often, using CDATA for language labels is the wrong way of doing things anyway IMO)
