### ISSUE TITLE
RFC: UX Feature: Sticky save button

### ISSUE THREAD

**Issue by nostadt** [rrrapha/translate_locallang#24]
When having lots of translations for a single file, the save button is not visible anymore - so, scrolling is necessary. I suggest to make the button sticky or perhaps add the save button along with the select fields to the `docheader`.

What are your thoughts about it?

**Comment by rrrapha** [comment]
I think moving the buttons to the docheader is nice ;)
@AMartinNo1 Could you please test if the develop branch works for you?

**Comment by nostadt** [comment]
@rrrapha Cool. I also like that you highlight the save button once there unsaved changes :+1:
