### ISSUE TITLE
RFC: Don't update the xlf date of unchanged languages

### ISSUE THREAD

**Issue by nostadt** [rrrapha/translate_locallang#26]
Assume setup:
Lang: de, en

For both languages xlf files exists. Now I make a change in EN. Once saving both xlf files gets updated. English with updated text and updated date-time and German with date-time.

Is there a specific reason to update the German file?

**Comment by rrrapha** [comment]
> Is there a specific reason to update the German file?

No, it's just simpler that way to keep the files in sync and nicely formatted. 
Checking if a file needs to be saved is not trivial, because of formatting and sorting.
(rendering to ram first, and comparing to the existing file would be possible, not sure if it's worth doing..)

**Comment by nostadt** [comment]
Keeping files in sync makes sense.
