### ISSUE TITLE
RFC: Feature: Information message for translators

### ISSUE THREAD

**Issue by nostadt** [rrrapha/translate_locallang#28]
In a real live scenario we have the situation that we need to keep two projects in sync. So as with the translations. We have two different repositories for reasons.

So, I had the thought it could be neat to provide a general information message for translators. One could provide contact partners within the company, or in our case reminder to keep two repositories in sync.

What do you think about this?

**Comment by nostadt** [comment]
I've created a PR. https://github.com/rrrapha/translate_locallang/pull/30

**Comment by rrrapha** [comment]
Thank you, I have merged PR. #30 into the develop branch.
