### ISSUE TITLE
More info about max_input_vars

### ISSUE THREAD

**Issue by liayn** [rrrapha/translate_locallang#3]
> Warning
> Too many labels, max_input_vars too small. Do not press save!

The warning is really nice, but two things come to my mind reading this:

- Why are the save buttons available at all then?
- How many labels do I have? What value should `max_input_vars` have?

**Comment by rrrapha** [comment]
Thank you, this is a nice improvement. 

What do you think about disabling the buttons instead of making them disappear? 
Something like this will gray out and disable the buttons (untested): 
`<f:form.submit disabled="{f:if(condition:'{enableSaveButtons}',then:'1',else:'')}" ... />`

**Comment by liayn** [comment]
@rrrapha pushed a new version.

PS: I suggest discussing implementation details directly in the PR and not in the issue ticket.
