### ISSUE TITLE
RFC: Add option to include sub directories

### ISSUE THREAD

**Issue by nostadt** [rrrapha/translate_locallang#32]
**Current behaviour:**

Only one level in Language directory is possible to maintain.

**What I want to do:**

Being able to categorize language files by topics. For example for custom content elements in a sub directory called `CType`.

**What is needed:**

Either all sub directories are considered by default or one can configure them somewhere. For example here: https://github.com/rrrapha/translate_locallang/blob/master/ext_conf_template.txt

```
# cat=basic//11; type=string; label=Additional sub directories
additionalSubDirectories = CType,AnOther/Path
```

**Comment by rrrapha** [comment]
@AMartinNo1 I have implemented this feature without configuration option. Does it work for you?

**Comment by nostadt** [comment]
Cool, thanks! Will check tomorrow :)

**Comment by nostadt** [comment]
Sorry, didn't had time yesterday. Hopefully this evening, so we can finish this asap :)

**Comment by nostadt** [comment]
Thanks, it's working.
