### ISSUE TITLE
Add option to configure csv delimiter

### ISSUE THREAD

**Issue by nostadt** [rrrapha/translate_locallang#39]
Unfortunately Google Drive does not support a lot of csv separator in the export feature.

https://github.com/rrrapha/translate_locallang/blob/014591f01f45437cd29ffb0f01b7dd604f6be5e2/Classes/Controller/ModuleController.php#L292

To be specific:

- comma
- tab

For now I can help myself for example using tab and replace the tab by semicolon. If it's possible to configure the delimiter in this extension it would be helpful though.

**Comment by rrrapha** [comment]
Thank you, see 58cf5eff3f09a2b6e0636f50d5e0e18c517eac0d.

**Comment by nostadt** [comment]
Thanks, that was fast :)
