### ISSUE TITLE
TYPO3 Extension Package "undefined/translate-locallang", does not define extension key in composer.json.

### ISSUE THREAD

**Issue by instance-pro** [rrrapha/translate_locallang#43]
Problem:
after update to the latest stable of TYPO3 packages, you get the following error: TYPO3 Extension Package "undefined/translate-locallang", does not define extension key in composer.json.

Solution:
add to composer.json
```json
	"extra": {
	   "typo3/cms": {
		  "extension-key": "translate_locallang"
	   }
	}
```

**Comment by rrrapha** [comment]
@instance-pro  I have commited a fix for this earlier today: https://github.com/rrrapha/translate_locallang/commit/d926d3e35de5d62749ce5c24fef8d7b7aec20fca
Did you get an error, or is it a warning?

**Comment by instance-pro** [comment]
it was an warning

**Comment by rrrapha** [comment]
Ok, thank you!
