### ISSUE TITLE
Request dedicated branch for v9 features

### ISSUE THREAD

**Issue by nostadt** [rrrapha/translate_locallang#44]
There are changes that are useful for v9 as well. For starters I can come up with the extension-key. In addition but perhaps arguably the XLF changes. A dedicated branch would allow to create further patches for this TYPO3 version.

What are your thoughts in that matter?

**Comment by rrrapha** [comment]
Hi @AMartinNo1, thanks for the suggestion.

To be honest, I don't think this would be very useful. I mean, you shouldn't be developing extensions for v9 anymore. ;)

My focus is on v11, and I think 2.7.3 still works fine for v9. 
The "xliff version 1.0" is correct for v9 and the missing "extension-key" is a deprecation-warning only. 

.. hmm, and I have no idea how this would work in non-composer mode.

**Comment by nostadt** [comment]
Thanks for your quick response.

While I see your point for new extensions we have four projects on v9 or shortly prior to upgrading to v9. While we definitely upgrade to v10 asap we will add features and update translation files before v10 upgrade and therefore it would come in handy.

However, I am aware that a new branch requires support time and this is open source. So up to you of course.

While it works without the extension key it gives noise when using composer.

**Comment by nostadt** [comment]
Update: Just talked to a colleague we have created patch(es) we use to make it work as we need. So even less need from our side for adjustments.

**Comment by rrrapha** [comment]
Cool, I'm glad you have found a solution. 
I still don't understand why you need any patches, .. but that's ok ;)

**Comment by nostadt** [comment]
We actually use XLF v1.2 already there and we wanted to get rid of the composer noise regarding the missing ext-key. Latter would not be fixabled by a composer patch. We created a private fork btw.

Once we upgrade to v10 we move back again to your repository :)
