### ISSUE TITLE
RFC: Don't update default language when useL10n=1

### ISSUE THREAD

**Issue by kitzberger** [rrrapha/translate_locallang#45]
Thanks for your work!

When setting `useL10n=1` the BE module writes the non-default languages into the folder `/var/www/var/labels/de/my_ext/Resources/Private/Language/xx.locallang.xlf` as expected.

Unfortunately the xlf of the default language (within the extensions folder!) is being updated as well. This makes it hard to use the extension in production ;-/

**Comment by dkern** [comment]
Absolutely true! I'm here to looking for exactly this too.
