### ISSUE TITLE
RFC: Add option to auto-sort from A-Z with each save

### ISSUE THREAD

**Issue by nostadt** [rrrapha/translate_locallang#49]
In the team we've decided to sort the keys from A-Z using the existing link / button. However, this requires a manual click at the moment which one easily forget. So, the idea I am having is to provide an extension setting with which one can enable auto sorting.

https://github.com/rrrapha/translate_locallang/blob/main/ext_conf_template.txt

```
# cat=basic//11; type=boolean; label=Auto sort from A-Z on save (default=false)
autoSortOnSave = false
```

Then around https://github.com/rrrapha/translate_locallang/blob/d75798db61ad6d7fff7785dc823bad3b83865ebb/Classes/Controller/ModuleController.php#L233 we would so sth. like:

```php
if ((bool)$extConf['autoSortOnSave']) {
  $xliffService->sortByKey();
}
```
This is untested. If I find time I'll test this and provide a PR.

**Comment by peter-neumann-dev** [comment]
We would be very excited about this option. This will also improve commits and code reviews since only the changed keys will get listed in change lists 👍

@rrrapha what do you think about this option?

**Comment by rrrapha** [comment]
I like the idea of this option. I will look into this soon. Auto-sorting could even be the default.

**Comment by rrrapha** [comment]
There is now an option called "sortOnSave".
