### ISSUE TITLE
Extensions without ext_emconf.php not found

### ISSUE THREAD

**Issue by nhovratov** [rrrapha/translate_locallang#59]
Since TYPO3 v11 this file is no longer necessary and only a composer.json file can be used.

**Comment by rrrapha** [comment]
I don't understand the issue, can you explain?
TYPO3 v10 is still supported, and even in v11, ext_emconf.php is needed for legacy installations.
See here:
https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/DeclarationFile/Index.html

**Comment by nhovratov** [comment]
sorry I forgot to answer. If you use composer-only mode in TYPO3 v11, it isn't mandatory anymore to provide a ext_emconf.php file. Those extensions won't be detected then. I had to add this file only so it can be found.

**Comment by rrrapha** [comment]
This should be fixed now (https://github.com/rrrapha/translate_locallang/commit/f75607dc4b776acab234b3357c14f73acb6f984a).
Sorry for the delay!
