### ISSUE TITLE
Backend module can not be opened

### ISSUE THREAD

**Issue by lneugebauer** [rrrapha/translate_locallang#60]
After installing the extension through composer I can not open the backend module. Instead I get the following error:
```
PHP Runtime Deprecation Notice: Required parameter $patterns follows optional parameter $allowedFiles in /path/to/public/typo3conf/ext/translate_locallang/Classes/Utility/TranslateUtility.php line 47
```

Environment:
- Apache 2.4.46
- PHP 8.0.13
- TYPO3 11.5.13

**Comment by rrrapha** [comment]
Thank you for reporting this!
