### ISSUE TITLE
Under TYPO3 11.x extensions might not be recognized

### ISSUE THREAD

**Issue by saneinsane** [rrrapha/translate_locallang#61]
`\Undefined\TranslateLocallang\Utility\TranslateUtility::isExtension` checks for existence of file `ext_emconf.php` but this file is needed only for legacy installations since version 11.5 (see [TYPO3 coreapi](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ExtEmconf.html#ext-emconf-php))

**Comment by rrrapha** [comment]
Thanks, this should now be fixed (https://github.com/rrrapha/translate_locallang/commit/f75607dc4b776acab234b3357c14f73acb6f984a).
