### ISSUE TITLE
No extensions listet if path to extensions is not typo3conf/ext

### ISSUE THREAD

**Issue by kimchristiansen** [rrrapha/translate_locallang#62]
I am using typo3/cms-composer-installers 4.0.0-RC1 where the extension are not stored in typo3conf/ext folder, instead in a different extensions folder and symlinked in the vendors folder.

Details on that is described here:
https://b13.com/core-insights/typo3-and-composer-weve-come-a-long-way

It seems that this causes the tranlsate_locallang not to find the extensions.

**Comment by rrrapha** [comment]
Hi @kimchristiansen , thanks for reporting.
Could you please check if 1a2ac548e03e82c11f3af50ca129287a7deb0a1c fixes the issue?

**Comment by kimchristiansen** [comment]
Thanks alot for the quick response!

All extensions are now listed for me. Below that is a selection of the xlf files of the selected extension.
But when I select the xlf file of my sitepackage extension and click on save, the following error message appears:

#1257246929 TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException

Tried resolving a template file for controller action "Standard->index" in format ".html", but none of the paths contained the expected template file ([project path]/www/public/typo3conf/ext/translate_locallang/Resources/Private/Templates/Xliff.html). No paths configured.

**Comment by rrrapha** [comment]
Thanks for testing! This should now be fixed in commit 6637d3a1c2fca4d08093dfcc82fa28f441fbfb00.

**Comment by kimchristiansen** [comment]
This commit has fixed the error. Great!
