### ISSUE TITLE
Bug: Switch files and choosing languages not working properly with TYPO3 v12

### ISSUE THREAD

**Issue by peter-neumann-dev** [rrrapha/translate_locallang#65]
After updating to TYPO3 v12 (PHP 8.2) it is not possible to select and switch to other files, or choose languages. The table is not updating. The only way to switch between files is to search for them in the additional submodule.

It appears that the event of the select fields is failing because of CSP:
<img width="741" alt="Peter Neumann 2023-05-30 at 18 57 24@2x" src="https://github.com/rrrapha/translate_locallang/assets/75690659/ab5dc762-53cf-469b-a9a7-d111eee694d8">

**Comment by peter-neumann-dev** [comment]
When removing the `additionalAttributes="{onchange:'this.form.submit()'}"` attributes in the `Filter.html` and adding something like this to the `translate.js` it seems to be working:
```javascript
const filterSelects = document.querySelectorAll('select[name="extkey"], select[name="file"], select[name="langKeys[]"]');

  filterSelects.forEach(select => {
    select.addEventListener('change', () => {
      const form = select.closest('form');
      form.submit();
    });
  });
```

**Comment by peter-neumann-dev** [comment]
@rrrapha What are your thoughts on switching to non-inline event listeners here?

**Comment by rrrapha** [comment]
> @rrrapha What are your thoughts on switching to non-inline event listeners here?

@peter-neumann-dev I think it is a good idea, i will look at your pull request soon. 
(BTW, I think it has nothing to do with updating to TYPO3 v12 or php version, it is your Webserver sending this CSP-Header.)
