### ISSUE TITLE
[Question/Suggestion] translated text from var/labels/ext does not show when useL10n = 0

### ISSUE THREAD

**Issue by medarob** [rrrapha/translate_locallang#77]
I wanted to look at the default translations for an extension and I noticed that they don't show up and I got a warning that it failed to load the language. The files where there and I didn't know, why there is an error loading the language files. This feels like a bug from an admin user perspective.

![grafik](https://github.com/rrrapha/translate_locallang/assets/33951787/9c3e7812-8ef6-4b0d-99e0-fb818f34b044)

I found out, that it depends wether the option `useL10n` is active or not. The translations are only shown when `useL10n` is active, even if an override of those standard crowdin labels isn't desired (that is why the option was deactivated in our case).

So, activating this option shows the text but that would mean that changes would be written in `var/labels/ext...` correct?
![grafik](https://github.com/rrrapha/translate_locallang/assets/33951787/7ed36da5-65ee-436e-a908-bf5034cf163f)

Even if the option `useL10n` will be deprecated in the future (as you mentioned) I would suggest that the default translations should be shown, regardless of the value of `use10Ln`. You can keep the red background, maybe make the field not editable to indicated, that there is default translation text from `var/labels/ext...` but it's not editable.

like:
![grafik](https://github.com/rrrapha/translate_locallang/assets/33951787/f8a3c354-6fc2-43ac-a921-58aefe027069)

And maybe add a warning that the current mode is `useL10n = 0` and you can't change the text in `var/labels/ext...`

**Comment by rrrapha** [comment]
The "useL10n" option has been removed. Thanks anyway for the report.
