### ISSUE TITLE
input fields are readonly in backend module

### ISSUE THREAD

**Issue by wowaTYPO3** [rrrapha/translate_locallang#81]
I have installed the extension in version 3.0.0 in a new project with TYPO3 13.3.0-dev.

But I cannot edit or create any keys. Because all input fields have the readonly attribute (see screenshot).

In another installation with TYPO3 13.3.0-dev it works.

I have already used the extension in several projects, but I have never had this problem.

![2024-07-24_14-25-06](https://github.com/user-attachments/assets/74ad4a84-9725-41ab-bd40-849a1066cbfc)

**Comment by rrrapha** [comment]
Thank you @wowaTYPO3. It seems like the problem has been fixed with commit https://github.com/TYPO3/Fluid/pull/940.
