### ISSUE TITLE
TYPO3Fluid\Fluid\View\Exception\InvalidTemplateResourceException

### ISSUE THREAD

**Issue by wowaTYPO3** [rrrapha/translate_locallang#83]
With TYPO3 13.3.0-dev and version 3.1.0 of your extension, I see the following error, when opening the backend module:

`
Tried resolving a template file for controller action "Default->Default" in format ".html", but none of the paths contained the expected template file (Default/Default.html). The following paths were checked: /var/www/html/vendor/typo3/cms-backend/Resources/Private/Templates/, /var/www/html/vendor/undefined/translate-locallang/Resources/Private/Templates/
`

In both directories there is no file Default.html

**Comment by rrrapha** [comment]
Maybe this has to be reverted: 9f8150b19cff5b8a1e4893a43a5e28e4ce77b43a
