### ISSUE TITLE
[Question] Why was useL10n option removed

### ISSUE THREAD

**Issue by ogrosko** [rrrapha/translate_locallang#84]
Hello,

why you removed plugin option `useL10n` **Save translations to 'labels' or 'l10n' folder instead of 'typo3conf/ext/'** from plugin version ^3

[commit](https://github.com/rrrapha/translate_locallang/commit/eb8a61d863eb3976b018314e67f80a5ffff73583)

We are used to using this option on every project

Thank you for the clarification

**Comment by rrrapha** [comment]
Hi @ogrosko

There is a conflict with the concept of "Language Packs", they use the same location to store translations, see here:
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/ManagingTranslations.html#xliff-translating-fetch

To override the labels of an extension, the following mechanism can be used instead:
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/ManagingTranslations.html#xliff-translating-custom

**Comment by devskio** [comment]
@rrrapha 

Do you have any other ideas on how to keep labels out of source control and keep them persisted after deploy ... 🤔

**Comment by ogrosko** [comment]
@rrrapha 

Do you have any other ideas on how to keep labels out of source control and keep them persisted after deploy ... 🤔

**Comment by Mabahe** [comment]
Hey @ogrosko, I use deployer and I configure the language files as shared https://deployer.org/docs/7.x/recipe/deploy/shared while the editors finalize them. When they are finished, I remove them in shared and they return to versioning.
