### ISSUE TITLE
Persistence logic - recommended setup for 12?

### ISSUE THREAD

**Issue by ursbraem** [rrrapha/translate_locallang#85]
@rrrapha Could you givea short summary of how the extension should be set up for TYPO3 12? I have lost the Overview a bit. 

We have two setups (not the same sites):

1) Sites that xlf files as code: edits with translate_locallang are made locally by the dev, committed and then deployed via pipeline to prod
2) Sites that treat xlf files as content: edits with translate_locallang are made on prod by editors and are stored outside the codebase in a "shared" folder 

Somehow, we got confused by the new storage locations with TYPO3 12, apparently translate_locallang stores data to vendor, where it is ignored?

**Comment by rrrapha** [comment]
Hi @ursbraem

That's a good question to which I don't have an good answer. 

The extension was meant to be used by extension developers only (use case number 1.), I wouldn't treat xlf files as content. 

Writing to _vendor_ is indeed weird, but I don't know how people are developing and testing extensions when in composer mode. 

Perhaps an external tool like https://github.com/garfieldius/t3ll is more suitable?

**Comment by ursbraem** [comment]
Thanks @rrrapha !

> Writing to vendor is indeed weird, but I don't know how people are developing and testing extensions when in composer mode.

So you say this might be an configuration error on our side? All we really need is use case 1, with the possibility to persist the edited xlfs in git. But this seems impossible atm, can that be?

Use case 2 is more of a nice to have for certain clients, could also be solved with editing labels on a translation server and loading them from there

**Comment by rrrapha** [comment]
> So you say this might be an configuration error on our side? 

No, it's not a configuration error, it's how it is working right now. Files are written to _vendor_ and you have to copy them somewhere to get them into your git repository.

**Comment by cepheiVV** [comment]
Could you imagine having this as a feature in your extension?
so we could set the path in the ext configuration.
Are you open for a PR in case we decide to implement this?

**Comment by rrrapha** [comment]
Hi @cepheiVV 
Yes, I'm open for this if it's not too complicated.

**Comment by ursbraem** [comment]
@rrrapha I have to decide if @cepheiVV provides the PR :-) 
Maybe it's the wrong approach to provide the local XLF editing via TYPO3 and we should focus on a standalone XLF editor? Are there any that can seamlessly handle the TYPO3 structure or is this exactly the reason why you created this extension?

**Comment by rrrapha** [comment]
@ursbraem The recommended editor is _t3ll_, see here:
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Localization/ManagingTranslations.html#xliff-translating-local

I have not tried it though ...

**Comment by ursbraem** [comment]
Oh! That looks quite similar to what you created!

![ScreenShot 2024-10-02 at 17 24 09](https://github.com/user-attachments/assets/486de6e1-ae46-46b5-b66c-45e8f57dd78e)

I did

```
brew tap garfieldius/taps
brew install t3ll
cd path/to/myproject/.../Language
t3ll locallang.xlf
```

And the GUI already came up.

**Comment by ursbraem** [comment]
It saves correctly and also updates the <source> in all files! I will ask my windows colleagues how it performs on win

**Comment by rrrapha** [comment]
> Oh! That looks quite similar to what you created!

Yes, it looks very similar ;-)

**Comment by ursbraem** [comment]
Hi @rrrapha 
Sorry, I had misunderstood the situation from the beginning. When we edit a custom extension or sitepackage, writing to vendor is not the case. This applies only for overrides when editing 3rd party / composer loaded extensions. 

But in this case, one can just create an override in their sitepackage and edit this.

t3ll and translate_locallang are fully equivalent here in the behaviour and so we stick to translate_locallang. 

Thanks for the patience!
